@startuml

skinparam ComponentStyle rectangle

component Mira {
    component SettlementControllers
}

note right
Static class, entry point for main script
Creates and manages settlement controllers
end note

component SettlementController {
    component BuildingSubcontroller
    note left of BuildingSubcontroller
    Processes requests to 
    build structures
    end note

    component TrainingSubcontroller
    note left of TrainingSubcontroller
    Processes requests to train units
    end note

    component MiningSubcontroller
    note left of MiningSubcontroller
    Provides resource gathering
    end note

    component StrategySubcontroller
    note left of StrategySubcontroller
    Eliminates enemy and 
    defends own settlement
    end note

    BuildingSubcontroller -[hidden]down-> TrainingSubcontroller
    TrainingSubcontroller -[hidden]down-> MiningSubcontroller
    MiningSubcontroller -[hidden]down-> StrategySubcontroller

    component CurrentState
    
    note bottom of CurrentState
    Defines current grand strategy,
    issues corresponding requests to
    subcontrollers

    (see Settlement Controller States
    diagram for reference)
    end note

    CurrentState -left-> BuildingSubcontroller
    CurrentState -left-> TrainingSubcontroller
    CurrentState -left-> MiningSubcontroller
    CurrentState -left-> StrategySubcontroller
}

note bottom of SettlementController
Coordinates current state and subcontrollers,
holds shared data
end note

SettlementControllers .down. SettlementController

@enduml
