@startuml controller states

state EXPLOIT {
    state Develop: Build-up economy
    state Defend: Defend against attacks
    state GatherUp: Build an army that\ncounters enemy strategy

    state Exploit_Entry <<inputPin>>

    Exploit_Entry --> Develop
    Develop --> Defend: Attacked
    Defend --> Develop: Attack countered
    GatherUp --> Defend: Attacked
    
    Develop --> GatherUp: Economy functioning
    GatherUp -down-> Exploit_ArmyGathered <<outputPin>>: Army gathered
}

note left of EXPLOIT
Building up economy,
gathering resources 
and training an army
end note

state EXPAND #pink: Choosing and securing expansion sites
state Exterminate: Attack the enemy

[*] -down-> Exploit_Entry: Initial state

Exploit_ArmyGathered -right-> Exterminate: Army gathered

Exterminate --> [*]: Enemy defeated
Exterminate --> Exploit_Entry: Army slain
Exterminate --> Defend: Main or expand attacked


legend
Pink and red colors mean that this 
state/transition is not implemented yet
endlegend

@enduml